/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ShopInfo = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrUpdateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getShopInfo' : IDL.Func([], [IDL.Opt(ShopInfo)], ['query']),
  'setShopInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProductAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateProductQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ShopInfo = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrUpdateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getShopInfo' : IDL.Func([], [IDL.Opt(ShopInfo)], ['query']),
    'setShopInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProductAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateProductQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };